In [2]:
#Escribir los modulos que se importan
import numpy as np
import numpy.linalg as ln

In [3]:
#Se desea estudiar la invertibilidad de la matriz A
A=np.array([[3,2,-3],[-3,-4,9],[-1,-2,5]])

In [4]:
A

array([[ 3,  2, -3],
       [-3, -4,  9],
       [-1, -2,  5]])

In [5]:
ln.det(A)

0.0

In [6]:
#La matriz no tiene inversa por lo tanto no puede calcularse ya que el determinante es igual a cero


In [7]:
#Sí se puede buscar la transpuesta y los autovalores y los autovectores
AT=np.transpose(A)
AT

array([[ 3, -3, -1],
       [ 2, -4, -2],
       [-3,  9,  5]])

In [8]:
autoA,vectA=ln.eig(A)

In [9]:
autoA

array([ 2.00000000e+00, -2.22044605e-16,  2.00000000e+00])

In [10]:
vectA

array([[ 0.6882472 ,  0.30151134, -0.435037  ],
       [-0.6882472 , -0.90453403,  0.80936038],
       [-0.22941573, -0.30151134,  0.39456125]])

In [11]:
#Comprobación de los autovalores. Debe cumplirse que det(A-x*I)=0
I=np.identity(3)

In [12]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
x=autoA[0]

In [14]:
ln.det(A-x*I)

-1.1832913578315107e-30

In [15]:
x=autoA[2]

In [16]:
ln.det(A-x*I)

-1.479114197289387e-30

In [17]:
#Ahora se desea resolver el sistema Cx=b
C=np.array([[-1,2,-3],[2,0,1],[3,-4,4]])
C

array([[-1,  2, -3],
       [ 2,  0,  1],
       [ 3, -4,  4]])

In [18]:
b=np.array([1,0,2])

In [19]:
ln.det(C)

10.000000000000002

In [20]:
x=np.dot(ln.inv(C),b)

In [21]:
x

array([ 0.8, -1.5, -1.6])

In [22]:
Cx=C.copy()
Cx[:,0]=b
Cx

array([[ 1,  2, -3],
       [ 0,  0,  1],
       [ 2, -4,  4]])

In [23]:
Cy=C.copy()
Cy[:,1]=b
Cy

array([[-1,  1, -3],
       [ 2,  0,  1],
       [ 3,  2,  4]])

In [24]:
Cz=C.copy()
Cz[:,2]=b
Cz

array([[-1,  2,  1],
       [ 2,  0,  0],
       [ 3, -4,  2]])

In [25]:
x1=ln.det(Cx)/ln.det(C)
y1=ln.det(Cy)/ln.det(C)
z1=ln.det(Cz)/ln.det(C)
print("la solucion es x={},y={},z={}".format(x1,y1,z1))

la solucion es x=0.7999999999999997,y=-1.5000000000000004,z=-1.6000000000000005
